_welcome:
    path:     /
    defaults: 
        { _controller: AcmeDemoBundle:Welcome:index }

_hello:
    path: hello/{A}/{B}
    defaults: 
        _controller: AcmeDemoBundle:Hello:sum

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
